name: Generate Daily Good News

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6am UTC
  workflow_dispatch:     # Allows you to run it manually anytime

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate daily good news
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_daily.py

      - name: Commit and push generated content
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/
          git commit -m "Daily update: Good News content"
          git push
