name: Generate Daily Good News

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6am UTC
  workflow_dispatch:     # Allows you to run it manually anytime

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate daily good news
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

        run: python generate_daily.py

      - name: Cleanup old files
        run: python scripts/cleanup_old_files.py

        
      - name: Commit and push generated content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/
          git diff --cached --quiet || git commit -m "Daily update: Good News content"
          # Set the token-based authentication
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
